// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);



namespace CountryData
{
    using System;
    using System.Collections.Generic;



    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;



    public partial class CountryCode
    {
        [JsonProperty("Code")]
        public string Code { get; set; }



        [JsonProperty("Name")]
        public string Name { get; set; }
    }



    public partial class CountryCode
    {
        public static CountryCode[] FromJson(string json) => JsonConvert.DeserializeObject<CountryCode[]>(json, CountryData.Converter.Settings);
    }



    public static class Serialize
    {
        public static string ToJson(this CountryCode[] self) => JsonConvert.SerializeObject(self, CountryData.Converter.Settings);
    }



    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}